apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::313015929039:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1S5E2ZFBR8R46
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::313015929039:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-10T15:37:57Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1733"
  uid: bb62baab-a9fb-454d-8387-3987e02ac037
